title: zjm's blog
description: about zjm's life
author: charming zhong
github: https://github.com/bfjm
about: Data mining
disqus_shortname: zjm
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/zjm.jpeg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/bfjm"

share:
  twitter_username:
  fb_appid: 

urls:
    - text: About Me
      url: /about/
    - text: Note
      url: /note/
    - text: Archive
      url: /archive/
    - text: Categories
      url: /categories/
    - text: tags
      url: /tags/


url: "https://bfjm.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
